let data = [
  {
    firstName: 'Sharon',
    lastName: 'Laurentin',
    email: 'slaurentin0@usgs.gov',
    gender: true,
    birthday: '2006-11-29',
  },
  {
    firstName: 'Francisca',
    lastName: 'Groocock',
    email: 'fgroocock1@github.com',
    gender: true,
    birthday: '2005-11-06',
  },
  {
    firstName: 'Alfy',
    lastName: 'Cristoferi',
    email: 'acristoferi2@4shared.com',
    gender: false,
    birthday: '2020-02-10',
  },
  {
    firstName: 'Mandy',
    lastName: 'Frugier',
    email: 'mfrugier3@ning.com',
    gender: true,
    birthday: '2011-08-16',
  },
  {
    firstName: 'Edlin',
    lastName: 'Starbuck',
    email: 'estarbuck4@jimdo.com',
    gender: false,
    birthday: '2001-08-25',
  },
  {
    firstName: 'Cody',
    lastName: 'Izkoveski',
    email: 'cizkoveski5@hc360.com',
    gender: false,
    birthday: '2001-07-23',
  },
  {
    firstName: 'Lezlie',
    lastName: "O'Deoran",
    email: 'lodeoran6@narod.ru',
    gender: true,
    birthday: '2004-09-03',
  },
  {
    firstName: 'Deena',
    lastName: 'Rau',
    email: 'drau7@tuttocitta.it',
    gender: false,
    birthday: '2004-05-18',
  },
  {
    firstName: 'Eugen',
    lastName: 'Olczak',
    email: 'eolczak8@hhs.gov',
    gender: false,
    birthday: '2009-09-14',
  },
  {
    firstName: 'Quintina',
    lastName: 'Betje',
    email: 'qbetje9@paginegialle.it',
    gender: true,
    birthday: '2013-07-09',
  },
  {
    firstName: 'Tarrah',
    lastName: 'Pirouet',
    email: 'tpiroueta@booking.com',
    gender: true,
    birthday: '2021-04-26',
  },
  {
    firstName: 'Quill',
    lastName: 'Kingh',
    email: 'qkinghb@themeforest.net',
    gender: false,
    birthday: '2003-08-29',
  },
  {
    firstName: 'Amata',
    lastName: 'Napolitano',
    email: 'anapolitanoc@msn.com',
    gender: true,
    birthday: '2012-06-03',
  },
  {
    firstName: 'Antonio',
    lastName: 'Lacy',
    email: 'alacyd@redcross.org',
    gender: true,
    birthday: '2008-08-01',
  },
  {
    firstName: 'Alison',
    lastName: 'Rodmell',
    email: 'arodmelle@wikimedia.org',
    gender: false,
    birthday: '2011-03-31',
  },
  {
    firstName: 'Ulrick',
    lastName: 'Wychard',
    email: 'uwychardf@ifeng.com',
    gender: true,
    birthday: '2006-07-13',
  },
  {
    firstName: 'Doria',
    lastName: 'Rudsdale',
    email: 'drudsdaleg@skyrock.com',
    gender: true,
    birthday: '2017-10-14',
  },
  {
    firstName: 'Joceline',
    lastName: 'Kynoch',
    email: 'jkynochh@bloglines.com',
    gender: false,
    birthday: '2004-09-14',
  },
  {
    firstName: 'Wood',
    lastName: 'Allkins',
    email: 'wallkinsi@fda.gov',
    gender: false,
    birthday: '2007-09-07',
  },
  {
    firstName: 'Daria',
    lastName: 'Cleevely',
    email: 'dcleevelyj@prnewswire.com',
    gender: false,
    birthday: '2001-10-07',
  },
  {
    firstName: 'Mariana',
    lastName: 'Beslier',
    email: 'mbeslierk@stumbleupon.com',
    gender: false,
    birthday: '2006-07-22',
  },
  {
    firstName: 'Rachel',
    lastName: 'Duffer',
    email: 'rdufferl@springer.com',
    gender: false,
    birthday: '2018-03-20',
  },
  {
    firstName: 'Karlen',
    lastName: 'Zohrer',
    email: 'kzohrerm@free.fr',
    gender: true,
    birthday: '2009-02-06',
  },
  {
    firstName: 'Decca',
    lastName: 'Ronayne',
    email: 'dronaynen@about.me',
    gender: false,
    birthday: '2012-12-08',
  },
  {
    firstName: 'Bryant',
    lastName: 'Rowan',
    email: 'browano@miitbeian.gov.cn',
    gender: true,
    birthday: '2004-06-18',
  },
  {
    firstName: 'Lyndel',
    lastName: 'Acors',
    email: 'lacorsp@home.pl',
    gender: true,
    birthday: '2020-09-07',
  },
  {
    firstName: 'Nikita',
    lastName: 'Kohrs',
    email: 'nkohrsq@alibaba.com',
    gender: true,
    birthday: '2011-09-05',
  },
  {
    firstName: 'Guillermo',
    lastName: 'Randleson',
    email: 'grandlesonr@cloudflare.com',
    gender: true,
    birthday: '2006-02-09',
  },
  {
    firstName: 'Ransom',
    lastName: 'Leaming',
    email: 'rleamings@vinaora.com',
    gender: false,
    birthday: '2013-04-22',
  },
  {
    firstName: 'Atalanta',
    lastName: 'Nayer',
    email: 'anayert@businessweek.com',
    gender: false,
    birthday: '2008-11-15',
  },
  {
    firstName: 'Armin',
    lastName: 'Daldan',
    email: 'adaldanu@google.ca',
    gender: false,
    birthday: '2021-04-24',
  },
  {
    firstName: 'Bruis',
    lastName: 'Norquay',
    email: 'bnorquayv@yahoo.co.jp',
    gender: false,
    birthday: '2021-11-01',
  },
  {
    firstName: 'Tamarra',
    lastName: 'Kubec',
    email: 'tkubecw@nydailynews.com',
    gender: true,
    birthday: '2022-04-18',
  },
  {
    firstName: 'Janene',
    lastName: 'Desquesnes',
    email: 'jdesquesnesx@odnoklassniki.ru',
    gender: true,
    birthday: '2005-01-21',
  },
  {
    firstName: 'Ollie',
    lastName: 'Ronald',
    email: 'oronaldy@t.co',
    gender: true,
    birthday: '2000-10-10',
  },
  {
    firstName: 'Ali',
    lastName: 'Bromige',
    email: 'abromigez@mysql.com',
    gender: false,
    birthday: '2009-07-17',
  },
  {
    firstName: 'Yank',
    lastName: 'Heibl',
    email: 'yheibl10@qq.com',
    gender: false,
    birthday: '2013-03-14',
  },
  {
    firstName: 'Melvyn',
    lastName: 'Fowkes',
    email: 'mfowkes11@free.fr',
    gender: true,
    birthday: '2009-07-29',
  },
  {
    firstName: 'Danell',
    lastName: 'Benstead',
    email: 'dbenstead12@cpanel.net',
    gender: false,
    birthday: '2014-09-27',
  },
  {
    firstName: 'Jarib',
    lastName: 'Bein',
    email: 'jbein13@un.org',
    gender: false,
    birthday: '2003-02-14',
  },
  {
    firstName: 'Delaney',
    lastName: 'Wilds',
    email: 'dwilds14@ucla.edu',
    gender: false,
    birthday: '2014-05-27',
  },
  {
    firstName: 'Ainslie',
    lastName: 'Iacapucci',
    email: 'aiacapucci15@bandcamp.com',
    gender: true,
    birthday: '2020-10-01',
  },
  {
    firstName: 'Katy',
    lastName: 'Milne',
    email: 'kmilne16@prlog.org',
    gender: true,
    birthday: '2016-10-24',
  },
  {
    firstName: 'Antonina',
    lastName: 'Scoble',
    email: 'ascoble17@usa.gov',
    gender: false,
    birthday: '2021-04-01',
  },
  {
    firstName: 'Pablo',
    lastName: 'Dymock',
    email: 'pdymock18@moonfruit.com',
    gender: true,
    birthday: '2014-10-19',
  },
  {
    firstName: 'Vivyan',
    lastName: 'Menier',
    email: 'vmenier19@naver.com',
    gender: true,
    birthday: '2009-09-26',
  },
  {
    firstName: 'Neille',
    lastName: 'Nortunen',
    email: 'nnortunen1a@earthlink.net',
    gender: false,
    birthday: '2005-02-03',
  },
  {
    firstName: 'Chrysa',
    lastName: 'Dainton',
    email: 'cdainton1b@boston.com',
    gender: true,
    birthday: '2011-10-30',
  },
  {
    firstName: 'Vasili',
    lastName: 'McGlaughn',
    email: 'vmcglaughn1c@yale.edu',
    gender: false,
    birthday: '2018-12-29',
  },
  {
    firstName: 'Giles',
    lastName: 'Ruddick',
    email: 'gruddick1d@wufoo.com',
    gender: true,
    birthday: '2010-01-12',
  },
  {
    firstName: 'Drake',
    lastName: 'Lumly',
    email: 'dlumly1e@live.com',
    gender: true,
    birthday: '2017-12-11',
  },
  {
    firstName: 'Lorri',
    lastName: 'Zorzenoni',
    email: 'lzorzenoni1f@pen.io',
    gender: false,
    birthday: '2015-07-31',
  },
  {
    firstName: 'Evvy',
    lastName: 'Peacop',
    email: 'epeacop1g@china.com.cn',
    gender: false,
    birthday: '2007-08-05',
  },
  {
    firstName: 'Tynan',
    lastName: 'Fogel',
    email: 'tfogel1h@cnet.com',
    gender: true,
    birthday: '2012-05-15',
  },
  {
    firstName: 'Margareta',
    lastName: 'Emberton',
    email: 'memberton1i@utexas.edu',
    gender: true,
    birthday: '2005-08-03',
  },
  {
    firstName: 'Marco',
    lastName: 'Scottrell',
    email: 'mscottrell1j@reddit.com',
    gender: true,
    birthday: '2017-01-20',
  },
  {
    firstName: 'Alli',
    lastName: 'Lukesch',
    email: 'alukesch1k@state.gov',
    gender: false,
    birthday: '2008-02-16',
  },
  {
    firstName: 'Fletch',
    lastName: 'Rennick',
    email: 'frennick1l@statcounter.com',
    gender: true,
    birthday: '2006-10-30',
  },
  {
    firstName: 'Melisandra',
    lastName: 'Diss',
    email: 'mdiss1m@virginia.edu',
    gender: true,
    birthday: '2015-02-01',
  },
  {
    firstName: 'Cymbre',
    lastName: 'Fruin',
    email: 'cfruin1n@vinaora.com',
    gender: true,
    birthday: '2012-10-03',
  },
  {
    firstName: 'Atlante',
    lastName: 'Sturror',
    email: 'asturror1o@yellowpages.com',
    gender: false,
    birthday: '2011-05-04',
  },
  {
    firstName: 'Mirelle',
    lastName: 'Quinevan',
    email: 'mquinevan1p@opensource.org',
    gender: false,
    birthday: '2016-08-04',
  },
  {
    firstName: 'Gavin',
    lastName: 'Island',
    email: 'gisland1q@edublogs.org',
    gender: true,
    birthday: '2019-10-18',
  },
  {
    firstName: 'Rubetta',
    lastName: 'Eytel',
    email: 'reytel1r@shutterfly.com',
    gender: false,
    birthday: '2020-02-21',
  },
  {
    firstName: 'Lind',
    lastName: 'Pherps',
    email: 'lpherps1s@google.co.jp',
    gender: false,
    birthday: '2004-10-26',
  },
  {
    firstName: 'Peta',
    lastName: 'Belt',
    email: 'pbelt1t@eepurl.com',
    gender: false,
    birthday: '2020-12-19',
  },
  {
    firstName: 'Read',
    lastName: 'Ingleson',
    email: 'ringleson1u@pen.io',
    gender: false,
    birthday: '2009-01-09',
  },
  {
    firstName: 'Becca',
    lastName: 'Hawyes',
    email: 'bhawyes1v@cisco.com',
    gender: false,
    birthday: '2014-10-09',
  },
  {
    firstName: 'Gerardo',
    lastName: 'Risson',
    email: 'grisson1w@stanford.edu',
    gender: true,
    birthday: '2010-06-14',
  },
  {
    firstName: 'Aarika',
    lastName: 'Fagg',
    email: 'afagg1x@disqus.com',
    gender: false,
    birthday: '2010-11-01',
  },
  {
    firstName: 'Ambrosio',
    lastName: 'Peetermann',
    email: 'apeetermann1y@usa.gov',
    gender: false,
    birthday: '2021-02-28',
  },
  {
    firstName: 'Kendrick',
    lastName: 'Hairsine',
    email: 'khairsine1z@pcworld.com',
    gender: false,
    birthday: '2001-06-16',
  },
  {
    firstName: 'Hollis',
    lastName: 'Phython',
    email: 'hphython20@nasa.gov',
    gender: true,
    birthday: '2011-06-06',
  },
  {
    firstName: 'Dita',
    lastName: 'Barhams',
    email: 'dbarhams21@pen.io',
    gender: true,
    birthday: '2009-03-24',
  },
  {
    firstName: 'Sterne',
    lastName: 'Bleiman',
    email: 'sbleiman22@spiegel.de',
    gender: false,
    birthday: '2008-01-10',
  },
  {
    firstName: 'Cy',
    lastName: 'Atkyns',
    email: 'catkyns23@stumbleupon.com',
    gender: false,
    birthday: '2014-12-28',
  },
  {
    firstName: 'Algernon',
    lastName: 'Beak',
    email: 'abeak24@hatena.ne.jp',
    gender: false,
    birthday: '2017-06-20',
  },
  {
    firstName: 'Theadora',
    lastName: 'Brothers',
    email: 'tbrothers25@ucsd.edu',
    gender: false,
    birthday: '2019-07-30',
  },
  {
    firstName: 'Lavena',
    lastName: 'Lanston',
    email: 'llanston26@stanford.edu',
    gender: false,
    birthday: '2011-02-09',
  },
  {
    firstName: 'Ulric',
    lastName: 'Walkling',
    email: 'uwalkling27@unblog.fr',
    gender: true,
    birthday: '2016-05-16',
  },
  {
    firstName: 'Travus',
    lastName: 'Jouanot',
    email: 'tjouanot28@wordpress.org',
    gender: true,
    birthday: '2008-04-06',
  },
  {
    firstName: 'Ilyssa',
    lastName: 'Beccera',
    email: 'ibeccera29@sina.com.cn',
    gender: true,
    birthday: '2016-11-29',
  },
  {
    firstName: 'Godwin',
    lastName: 'McWilliams',
    email: 'gmcwilliams2a@arizona.edu',
    gender: true,
    birthday: '2001-05-17',
  },
  {
    firstName: 'Kasper',
    lastName: 'Sudddard',
    email: 'ksudddard2b@discovery.com',
    gender: true,
    birthday: '2004-05-22',
  },
  {
    firstName: 'Sampson',
    lastName: 'Winterborne',
    email: 'swinterborne2c@sogou.com',
    gender: false,
    birthday: '2021-01-08',
  },
  {
    firstName: 'Curcio',
    lastName: 'Goldwater',
    email: 'cgoldwater2d@uiuc.edu',
    gender: false,
    birthday: '2008-12-01',
  },
  {
    firstName: 'Karyl',
    lastName: 'Dabel',
    email: 'kdabel2e@slashdot.org',
    gender: false,
    birthday: '2012-01-08',
  },
  {
    firstName: 'Doloritas',
    lastName: "O'Cosgra",
    email: 'docosgra2f@wikispaces.com',
    gender: true,
    birthday: '2021-06-04',
  },
  {
    firstName: 'Kirsten',
    lastName: 'Welch',
    email: 'kwelch2g@hp.com',
    gender: true,
    birthday: '2013-07-11',
  },
  {
    firstName: 'Granny',
    lastName: 'Casoni',
    email: 'gcasoni2h@msu.edu',
    gender: false,
    birthday: '2017-04-15',
  },
  {
    firstName: 'Merrel',
    lastName: 'Drewitt',
    email: 'mdrewitt2i@intel.com',
    gender: false,
    birthday: '2021-11-08',
  },
  {
    firstName: 'Sergio',
    lastName: 'Oldrey',
    email: 'soldrey2j@umn.edu',
    gender: false,
    birthday: '2016-11-16',
  },
  {
    firstName: 'Deana',
    lastName: 'Ferruzzi',
    email: 'dferruzzi2k@rambler.ru',
    gender: true,
    birthday: '2017-10-06',
  },
  {
    firstName: 'Aguie',
    lastName: 'Watson',
    email: 'awatson2l@baidu.com',
    gender: false,
    birthday: '2016-01-19',
  },
  {
    firstName: 'Lovell',
    lastName: 'Roset',
    email: 'lroset2m@chronoengine.com',
    gender: true,
    birthday: '2011-05-04',
  },
  {
    firstName: 'Forester',
    lastName: 'Twohig',
    email: 'ftwohig2n@sciencedaily.com',
    gender: false,
    birthday: '2010-10-01',
  },
  {
    firstName: 'Briano',
    lastName: 'Klaessen',
    email: 'bklaessen2o@hubpages.com',
    gender: false,
    birthday: '2008-07-04',
  },
  {
    firstName: 'Darlleen',
    lastName: 'Gowdy',
    email: 'dgowdy2p@senate.gov',
    gender: true,
    birthday: '2015-12-11',
  },
  {
    firstName: 'Alia',
    lastName: 'Leddy',
    email: 'aleddy2q@scientificamerican.com',
    gender: true,
    birthday: '2005-09-06',
  },
  {
    firstName: 'Carree',
    lastName: 'Barszczewski',
    email: 'cbarszczewski2r@xinhuanet.com',
    gender: false,
    birthday: '2020-11-12',
  },
]

data = data.map((item) => ({
  ...item,
  username: (item.firstName + '-' + item.lastName).replace(/ /g, '').toLowerCase(),
  password: '12345678',
  avatar: 'https://picsum.photos/300/300',
  photos: [
    'https://picsum.photos/200/300',
    'https://picsum.photos/300/300',
    'https://picsum.photos/400/300',
  ],
}))

export default data
